version: '3.8'

services:
  bdd:
    image: mysql:8.0
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: allocine
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  web:
    build: ./web
    platform: linux/amd64
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - bdd

  pma:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    environment:
      PMA_HOST: bdd
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - bdd

volumes:
  db_data:
